export const dataStories = [
    {
      id: "1",
      image: "data.pic5.childImageSharp.fluid",
      name: "Barbara",
      weight: "-40 kg",
      cardTeaser: "cardTeaser",
      text: "text sample",
    },
    {
      id: "2",
      image: "data.pic6.childImageSharp.fluid",
      name: "Kasia",
      weight: "-30kg",
      cardTeaser: "cardTeaser",
      text: "text sample",
      },
    // {
    //   id: "3",
    //   image: "link or tag",
    //   name: "Kasia",
    //   weight: "-40",
    //   cardTeaser: "cardTeaser",
    //   text: "text sample",
    //   name: "name name",
    // },
    // {
    //   id: "4",
    //   image: "link or tag",
    //   name: "Kasia",
    //   weight: "-40",
    //   cardTeaser: "cardTeaser",
    //   text: "text sample",
    //   name: "name name",
    // },
    // {
    //   id: "5",
    //   image: "link or tag",
    //   name: "Kasia",
    //   weight: "-40",
    //   cardTeaser: "cardTeaser",
    //   text: "text sample",
    //   name: "name name",
    // },
    // {
    //   id: "6",
    //   image: "link or tag",
    //   name: "Kasia",
    //   weight: "-40",
    //   cardTeaser: "cardTeaser",
    //   text: "text sample",
    //   name: "name name",
    // },
    // {
    //   id: "7",
    //   image: "link or tag",
    //   name: "Kasia",
    //   weight: "-40",
    //   cardTeaser: "cardTeaser",
    //   text: "text sample",
    //   name: "name name",
    // },
    // {
    //   id: "8",
    //   image: "link or tag",
    //   name: "Kasia",
    //   weight: "-40",
    //   cardTeaser: "cardTeaser",
    //   text: "text sample",
    //   name: "name name",
    // },
  ];